# Generated by Django 5.1.6 on 2025-04-25 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("e_commerce_app", "0002_admin"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="admin",
            name="address",
        ),
        migrations.RemoveField(
            model_name="admin",
            name="username",
        ),
    ]
