# Generated by Django 5.1.6 on 2025-04-25 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("e_commerce_app", "0003_remove_admin_address_remove_admin_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="admin",
            name="Address",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="e_commerce_app.address",
            ),
        ),
        migrations.AddField(
            model_name="admin",
            name="username",
            field=models.CharField(default="", max_length=50),
        ),
    ]
