# Generated by Django 5.1.6 on 2025-04-25 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("e_commerce_app", "0005_alter_product_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="expirationDate",
        ),
        migrations.RemoveField(
            model_name="product",
            name="fabricationDate",
        ),
        migrations.DeleteModel(
            name="admin",
        ),
    ]
