# Generated by Django 5.1.6 on 2025-04-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("e_commerce_app", "0007_admin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admin",
            name="address",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="provider",
            name="address",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="client",
            name="address",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.DeleteModel(
            name="Address",
        ),
    ]
