# Generated by Django 5.1.6 on 2025-04-26 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("e_commerce_app", "0008_alter_admin_address_alter_provider_address_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="provider",
            name="site_url",
        ),
    ]
